FROM node:20-alpine

# Set working directory
WORKDIR /app

# Install dependencies needed for node-gyp and libc6-compat
RUN apk add --no-cache libc6-compat

# Copy package files
COPY package.json package-lock.json* ./
COPY prisma ./prisma

# Install dependencies
RUN npm install

# Copy source code (optional since we use volumes, but good for initial build)
COPY . .

# Generate Prisma client
RUN npx prisma generate

# Expose port
EXPOSE 3000

ENV PORT=3000
ENV HOSTNAME="0.0.0.0"

# Command to run development server
CMD ["npm", "run", "dev"]
